package com.germani.dit.node.repo.db.model

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

@Document(collection = "node-chain")
class ChainEntity(
    var initNode: ChainUnitEntity
) {
    //TODO: id Long autogenerated
    @Id
    var id: String? = null

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ChainEntity

        if (initNode != other.initNode) return false
        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        var result = initNode.hashCode()
        result = 31 * result + (id?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String {
        return "NodeChain(nodes=$initNode, id=$id)"
    }
}